# Generated by Django 3.1.4 on 2021-02-04 03:50

import delegate.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0006_auto_20210203_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resolution', models.JSONField(default=delegate.models.Reso.reso_default)),
                ('name', models.CharField(default='default_reso_name', max_length=30)),
                ('<django.db.models.fields.CharField>_<django.db.models.fields.AutoField>', models.FileField(blank=True, null=True, upload_to=delegate.models.Reso.file_path)),
                ('committee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.committee')),
            ],
        ),
    ]
