# Generated by Django 3.1.4 on 2021-02-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegate', '0003_reso_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reso',
            name='file_path',
            field=models.CharField(default='DEFAULT2021/DEFAULT1/resolutions', max_length=500),
        ),
        migrations.AlterField(
            model_name='reso',
            name='resolution_file',
            field=models.FileField(blank=True, null=True, upload_to=models.CharField(default='DEFAULT2021/DEFAULT1/resolutions', max_length=500), verbose_name='Resolution File'),
        ),
    ]
