# Generated by Django 3.1.4 on 2021-02-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delegate', '0004_auto_20210204_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reso',
            name='file_path',
        ),
        migrations.AlterField(
            model_name='reso',
            name='resolution_file',
            field=models.FileField(blank=True, null=True, upload_to='DEFAULT2021/DEFAULT1/resolutions', verbose_name='Resolution File'),
        ),
    ]
