# Generated by Django 3.1.4 on 2021-01-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='committees',
        ),
        migrations.AddField(
            model_name='committee',
            name='countries',
            field=models.ManyToManyField(to='homepage.Country'),
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('abbr', models.CharField(max_length=15)),
                ('committees', models.ManyToManyField(to='homepage.Committee')),
            ],
            options={
                'ordering': ['abbr'],
            },
        ),
    ]
