# Generated by Django 3.1.4 on 2021-01-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201231_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='conf_id',
            field=models.CharField(default='defaultconfid', max_length=20),
            preserve_default=False,
        ),
    ]
