# Generated by Django 3.1.4 on 2021-01-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20210102_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='logo',
            field=models.ImageField(null=True, upload_to='conference/logos'),
        ),
    ]
