# Generated by Django 3.1.4 on 2021-02-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_conference_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='chairs',
            field=models.ManyToManyField(blank=True, to='homepage.Chair'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='countries',
            field=models.ManyToManyField(blank=True, to='homepage.Country'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='committees',
            field=models.ManyToManyField(blank=True, to='homepage.Committee'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='conference/logos'),
        ),
    ]
